version: "3.9"
services:
  postgres:
    image: postgr-db:v1.0
    environment:
      POSTGRES_DB: "chain"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
  app:
    image: app:v1.0
    depends_on:
      - db
    ports:
      - "5000:5000"
